routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['isAdmin']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/delete-rubric/{id}', 'TrashController@destroyRubric');
	Route::get('/delete-type/{id}', 'TrashController@destroyType');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/delete-news/{id}', 'TrashController@destroyNews');
	Route::get('/restore-rubric/{id}', 'TrashController@restoreRubric');
	Route::get('/restore-type/{id}', 'TrashController@restoreType');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::get('/restore-news/{id}', 'TrashController@restoreNews'); 

	//Rubrik Controller
	Route::resource('/rubric', 'RubricController');
	Route::get('/rubric-order', 'RubricController@rubricOrder');
	Route::post('/rubric-order-save', 'RubricController@orderSave');
	//End Rubrik Controller

	//Tipe Controller
	Route::resource('/type', 'TypeController');
	//End Tipe Controller

	//Highlight Controller
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	//End Highlight Controller

	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	//End News Controller

	//Ads Controller
	Route::resource('/advertisement', 'AdvertisementController');
	//End Ads Controller

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::post('/spread-news/{news}', 'SubscribeController@spreadNews');

	//AccessLog
	Route::resource('/accesslog', 'AccessLogController');
	Route::post('/accesslog/export', 'AccessLogController@export');
	Route::post('/accesslog/delete', 'AccessLogController@delete');

	//Config
	Route::get('/config', 'ConfigController@index');
	Route::post('/config/update/{id}', 'ConfigController@update');
	Route::get('/log', 'LogController@index');
});

Route::group(['middleware' => ['isRedaktur']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	
	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	
	Route::resource('/profile', 'ProfileController'); 

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::get('/spread-news/{news}', 'SubscribeController@spreadNews');
	Route::get('/log', 'LogController@index');
});  
 
Route::group(['middleware' => ['isReporter']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 

Route::group(['middleware' => ['isUser']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 


//FRONT END 
Route::get('/', 'FrontEnd\IndexController@index');
Route::post('/user-store', 'UserController@userStore');
Route::post('/subscribe', 'SubscribeController@postSubscribe');
Route::get('berita/rubrik/{rubric}', 'FrontEnd\RubrikController@index');
Route::get('berita/rubrik/{rubric}/{news}', 'FrontEnd\NewsController@rubric_news');
Route::get('berita/fokus/{highlight}', 'FrontEnd\FokusController@index');
Route::get('berita/fokus/{highlight}/{news}', 'FrontEnd\NewsController@highlight_news');
Route::resource('/subscribe', 'SubscribeController');
Route::resource('/comment', 'CommentController');
Route::get('/request-ads', function(){
	Alert::message('Silahkan hubungi kami melalui email untuk pemasangan iklan di portal kami. Email : retorikakampus@gmail.com', 'Permohonan Izin Iklan')->persistent('Close');
	return redirect('/');
});
Route::get('/pencarian', 'SearchController@searchResult');
Route::get('/pencarian/berita', 'SearchController@searchNews');
Route::get('/pencarian/komentar', 'SearchController@searchComments');

app/Advertisement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Advertisement extends Model
{
    protected $fillable = [
    	'type',
        'order',
    	'title',
    	'description',
    	'image',
    	'url'
    ];

    public function getPhotoPathAttribute(){
        if($this->image != ''){
            return url('/img/data/advertisement/'.$this->image);
        }
        else if($this->image == NULL){
            return url('/img/data/advertisement/default.png');
        }
        else{
            return url('/img/data/advertisement/default.png');
        }
    } 
}

app/Http/Controllers/AdvertisementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Advertisement;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Session;
use Auth;
use Validator;
use File;

class AdvertisementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $advertisements = Advertisement::orderBy('created_at', 'desc')->paginate(5);
            return view('advertisement.index', compact('advertisements'));
        }
        // catch (\Illuminate\Database\QueryException $e) {
        //     return \Response::view('errors.query',array(),500);
        // }
        catch (\Exception $e) {
            return \Response::view('errors.500',array(),500);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title' => 'required|string|max:255|unique:advertisements',
            'type' => 'required|in:depan,rubrik,berita,fokus',
            'image' => 'image|mimes:jpeg,jpg,png,gif|max:5000|',
            'url' => 'url|unique:advertisements',
            'description' => 'string|max:255',
            'order' => 'numeric|in:1,2,3,4,5'
        ];

        $messages = [
            'required' => 'Field harus di isi alias tidak boleh kosong',
            'image' => 'Data harus berbenuk gambar',
            'unique' => 'Data sudah ada dalam database', 
            'mimes' => 'Image harus berekstensi JPEG, JPG, dan PNG',
            'url' => 'URL tidak valid',
            'in' => 'Order melebihi batas'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if($validator->fails()) {
            Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal menambahkan data advertisement"]);
            return redirect() -> route('advertisement.index')->withErrors($validator)->withInput();
        }

        $advertisements = Advertisement::all();
        $check_advertisement = Advertisement::where('type', $request->type)->where('order', $request->order)->count();
        if($check_advertisement) {
            Session::flash('flash_notification', ["level"=>"danger", "message"=>"Order dengan tipe yang sama sudah ada"]);
            return redirect()->route('advertisement.index')->withInput();        
        }

        $data = $request->except(['image']);
        if ($request->hasFile('image')){
            $data['image'] = $this->savePhoto($request->file('image'));
        } 

        $advertisement = Advertisement::create($data);
        if($advertisement){
            Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil menambahkan advertisement '".$request->title."' kedalam database"]);
            return redirect()->route('advertisement.index');
        }
        else{
            Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal menambahkan advertisement"]);
            return redirect()->route('advertisement.index')->withInput();  
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'title' => 'required|string|max:255|unique:advertisements,title,'.$id,
            'type' => 'required|in:depan,rubrik,berita,fokus',
            'image' => 'image|mimes:jpeg,jpg,png,gif|max:5000|',
            'url' => 'url|unique:advertisements,url,'.$id,
            'description' => 'string|max:255',
            'order' => 'numeric|in:1,2,3,4,5'
        ];

        $messages = [ 
            'required' => 'Field harus di isi alias tidak boleh kosong',
            'image' => 'Data harus berbenuk gambar',
            'unique' => 'Data sudah ada dalam database', 
            'mimes' => 'Image harus berekstensi JPEG, JPG, dan PNG',
            'url' => 'URL tidak valid'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if($validator->fails()) {
            Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah advertisement"]);
            return redirect() -> route('advertisement.index')->withErrors($validator)->withInput();
        }

        $advertisement = Advertisement::find($id);
        if($advertisement->type != $request->type or $advertisement->order != $request->order){
            $check_advertisement = Advertisement::where('type', $request->type)->where('order', $request->order)->count();
        }
        else{
            $check_advertisement = 0;
        }

        if($check_advertisement) {
            Session::flash('flash_notification', ["level"=>"danger", "message"=>"Order dengan tipe yang sama sudah ada"]);
            return redirect()->route('advertisement.index')->withInput();        
        }

        $olddata = Advertisement::find($id);
        $data = $request->except(['image']);
        if ($request->hasFile('image')){
            $data['image'] = $this->savePhoto($request->file('image'));
            if($olddata->image !== '') $this->deletePhoto($olddata->image);
        } 

        $advertisement = $advertisement->update($data);
        if($advertisement){
            Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil mengubah data advertisement kedalam database"]);
            return redirect()->route('advertisement.index');    
        }
        else {
            Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah advertisement"]);
            return redirect() -> route('advertisement.index')->withErrors($validator)->withInput();   
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { 
        $data = Advertisement::find($id);
        $advertisement = Advertisement::find($id)->delete();
        if($advertisement){
            if($data->image !== '') $this->deletePhoto($data->image);
            Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil menghapus advertisement '".$data->title."'"]);
            return redirect()->route('advertisement.index');
        }
        else {
            Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal menghapus advertisement"]);
            return redirect() -> route('advertisement.index')->withErrors($validator)->withInput();   
        }
    }

    public function savePhoto(UploadedFile $photo) {
        $fileName = str_random(40) . '.' . $photo->guessClientExtension();
        $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img/data/advertisement';
        $photo -> move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename){
        $path = public_path() . DIRECTORY_SEPARATOR . 'img/data/advertisement/'.$filename;
        return File::delete($path);
    }

}

resources/views/advertisement/form.blade.php
<div class= " form-group { !! $errors->has('title') ? 'has-error' : '' !!}">
	{!! Form::label('title', 'Title') !!}
	{!! Form::text('title',  null, ['class' =>'form-control', 'placeholder' => 'Ketik judul iklan...']) !!}
	{!! $errors->first('title', '<p class="help-block">:message</p>') !!}
</div>

<div class= " form-group {!! $errors->has('type') ? 'has-error' : '' !!}">
	{!! Form::label('type', 'Type') !!}
	{!! Form::select('type', ['depan' => 'Depan','rubrik' => 'Rubrik','berita' => 'Berita', 'fokus' => 'Fokus'], null, ['class' =>'form-control js-selectize']) !!}
	{!! $errors->first('type', '<p class="help-block">:message</p>') !!}
</div> 

<div class= " form-group { !! $errors->has('order') ? 'has-error' : '' !!}">
	{!! Form::label('order', 'Order') !!}
	{!! Form::number('order',  null, ['class' =>'form-control','onkeypress'=>'return event.charCode >= 48', 'min'=>'1']) !!}
	{!! $errors->first('order', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('image') ? 'has-error' : '' !!}">
	{!! Form::label('image', 'Image ( jpg,jpeg,png )') !!}
	{!! Form::file('image') !!}
	{!! $errors->first('image', '<p class="help-block">:message</p>')  !!}
	@if (isset($model) && $model->image !== '' )
	<div class= "row">
		<div class= "col-md-6">
			<br>
			<p>Current iamge:</p>
			<div class= "thumbnail">
				<img src = "{{ url('/img/highlight/' . $model->image) }}" class="img-rounded" width="200" height="200">
			</div>
		</div>
	</div>
	@endif
	@if (isset($model) && $model->image == '')
	<div class= "row">
		<div class= "col-md-6">
			<br>
			<p>Current image:</p>
			<div class= "thumbnail">
				<img src = "{{ url('/img/data/advertisement/default.png') }}" class="img-rounded" width="200" height="200">
			</div>
		</div>
	</div>
	@endif
</div>

<div class= " form-group { !! $errors->has('url') ? 'has-error' : '' !!}">
	{!! Form::label('url', 'Url') !!}
	{!! Form::text('url',  null, ['class' =>'form-control', 'placeholder' => 'Contoh: http://www.iklanku.com']) !!}
	{!! $errors->first('url', '<p class="help-block">:message</p>') !!}
</div>

<div class= " form-group { !! $errors->has('description') ? 'has-error' : '' !!}">
	{!! Form::label('description', 'Description') !!}
	{!! Form::text('description',  null, ['class' =>'form-control', 'placeholder' => 'Tuliskan deskripsi iklan..']) !!}
	{!! $errors->first('description', '<p class="help-block">:message</p>') !!}
</div>

resources/views/advertisement/index.blade.php
@extends('layouts.app2')
@section('title', 'advertisements')
@section('menu', 'advertisements')
@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Advertisements
            </h3>
            <div class="btn-group pull-right">
                <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i> Export Data</button>
                <ul class="dropdown-menu">
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'json',escape:'false'});"><img src='img/icons/json.png' width="24"/> JSON</a></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'json',escape:'false',ignoreColumn:'[2,3]'});"><img src='img/icons/json.png' width="24"/> JSON (ignoreColumn)</a></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'json',escape:'true'});"><img src='img/icons/json.png' width="24"/> JSON (with Escape)</a></li>
                    <li class="divider"></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'xml',escape:'false'});"><img src='img/icons/xml.png' width="24"/> XML</a></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'sql'});"><img src='img/icons/sql.png' width="24"/> SQL</a></li>
                    <li class="divider"></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'csv',escape:'false'});"><img src='img/icons/csv.png' width="24"/> CSV</a></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'txt',escape:'false'});"><img src='img/icons/txt.png' width="24"/> TXT</a></li>
                    <li class="divider"></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'excel',escape:'false'});"><img src='img/icons/xls.png' width="24"/> XLS</a></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'doc',escape:'false'});"><img src='img/icons/word.png' width="24"/> Word</a></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'powerpoint',escape:'false'});"><img src='img/icons/ppt.png' width="24"/> PowerPoint</a></li>
                    <li class="divider"></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'png',escape:'false'});"><img src='img/icons/png.png' width="24"/> PNG</a></li>
                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'pdf',escape:'false'});"><img src='img/icons/pdf.png' width="24"/> PDF</a></li>
                </ul>
            </div>                                     
        </div>
        <div class="panel-body">
            <span>Tambah: 
                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalCreate">
                  +
                </button>                
                <div class="modal fade" id="modalCreate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                      </div>
                      {!! Form::open(['route' => 'advertisement.store', 'files'=>true]) !!}
                          <div class="modal-body">
                            @include('advertisement.form')
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                          </div>
                      {!! Form::close() !!} 
                    </div>
                  </div>
                </div>
            <span>
            <div class="table-responsive"> 
                <table id="customers2" class="table datatable">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Image</th>
                            <th>Url</th>
                            <th>Type</th>
                            <th>Order</th>
                            <th>Created at</th>
                            <th>Updated at</th>
                            <th colspan="2"><center>Action</center></th>
                        </tr>
                    </thead>
                    <tbody> 
                        @forelse($advertisements as $key=>$advertisement)
                        <tr>
                            @php $key = $key+ 1 @endphp
                            <td>{{ $advertisement -> title }}</td>
                            <td><img src="{{ $advertisement -> photo_path }}" alt="..." width="50" height="50" class="img-responsive"></td>
                            <td>{{ $advertisement -> url }}</td>
                            <td>{{ $advertisement -> type }}</td>
                            <td>{{ $advertisement -> order }}</td>
                            <td>{{ $advertisement -> created_at }}</td>
                            <td>{{ $advertisement -> updated_at }}</td>
                            <td>
                                {{-- <a href="{{ route('advertisement.edit', $advertisement->id) }}" class = "btn btn-sm btn-success">Edit</a> --}}
                                <button type="button" class="btn btn-primary btn-sm" id='<?php echo $key; ?>' onClick="edit_click(this.id)"'>Edit</button>               
                                <div class="modal fade" id="modalEdit{{$key}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Edit advertisement</h4>
                                      </div>
                                      {!! Form::model($advertisement, ['route'=> ['advertisement.update', $advertisement], 'method'=>'patch', 'files'=>true]) !!}
                                          <div class="modal-body">
                                                @include('advertisement.form')
                                          </div>

                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                          </div>
                                      {!! Form::close() !!}
                                    </div>
                                  </div>
                                </div>
                            </td>
                            <td>
                                {!! Form::model($advertisement, ['route' => ['advertisement.destroy', $advertisement], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                                {!! Form::submit('delete', ['class'=>'btn btn-sm btn-danger js-submit-confirm']) !!}
                                {!! Form::close() !!}
                            </td> 
                        </tr>
                        @empty
                        <tr>
                        <td colspan="8">
                        <center><h2>:(</h2><br>Daftar iklan masih kosong</center>
                        </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table> 
                {{ $advertisements->links() }}                                   
            </div>
        </div>
    </div>
@endsection

@section('script')
<script type='text/javascript' src="{{ asset('js/plugins/icheck/icheck.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/tableexport/tableExport.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jquery.base64.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/tableexport/html2canvas.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jspdf/libs/sprintf.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jspdf/jspdf.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jspdf/libs/base64.js') }}"></script>  
<script type="text/javascript" src="{{ asset('js/actions.js') }}"></script> 
<script type="text/javascript">
    function edit_click(id)
    {
        $("#modalEdit"+id).modal();
    }
</script>
@endsection 