routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['isAdmin']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/delete-rubric/{id}', 'TrashController@destroyRubric');
	Route::get('/delete-type/{id}', 'TrashController@destroyType');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/delete-news/{id}', 'TrashController@destroyNews');
	Route::get('/restore-rubric/{id}', 'TrashController@restoreRubric');
	Route::get('/restore-type/{id}', 'TrashController@restoreType');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::get('/restore-news/{id}', 'TrashController@restoreNews'); 

	//Rubrik Controller
	Route::resource('/rubric', 'RubricController');
	Route::get('/rubric-order', 'RubricController@rubricOrder');
	Route::post('/rubric-order-save', 'RubricController@orderSave');
	//End Rubrik Controller

	//Tipe Controller
	Route::resource('/type', 'TypeController');
	//End Tipe Controller

	//Highlight Controller
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	//End Highlight Controller

	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	//End News Controller

	//Ads Controller
	Route::resource('/advertisement', 'AdvertisementController');
	//End Ads Controller

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::post('/spread-news/{news}', 'SubscribeController@spreadNews');

	//AccessLog
	Route::resource('/accesslog', 'AccessLogController');
	Route::post('/accesslog/export', 'AccessLogController@export');
	Route::post('/accesslog/delete', 'AccessLogController@delete');

	//Config
	Route::get('/config', 'ConfigController@index');
	Route::post('/config/update/{id}', 'ConfigController@update');
	Route::get('/log', 'LogController@index');
});

Route::group(['middleware' => ['isRedaktur']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	
	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	
	Route::resource('/profile', 'ProfileController'); 

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::get('/spread-news/{news}', 'SubscribeController@spreadNews');
	Route::get('/log', 'LogController@index');
});  
 
Route::group(['middleware' => ['isReporter']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 

Route::group(['middleware' => ['isUser']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 


//FRONT END 
Route::get('/', 'FrontEnd\IndexController@index');
Route::post('/user-store', 'UserController@userStore');
Route::post('/subscribe', 'SubscribeController@postSubscribe');
Route::get('berita/rubrik/{rubric}', 'FrontEnd\RubrikController@index');
Route::get('berita/rubrik/{rubric}/{news}', 'FrontEnd\NewsController@rubric_news');
Route::get('berita/fokus/{highlight}', 'FrontEnd\FokusController@index');
Route::get('berita/fokus/{highlight}/{news}', 'FrontEnd\NewsController@highlight_news');
Route::resource('/subscribe', 'SubscribeController');
Route::resource('/comment', 'CommentController');
Route::get('/request-ads', function(){
	Alert::message('Silahkan hubungi kami melalui email untuk pemasangan iklan di portal kami. Email : retorikakampus@gmail.com', 'Permohonan Izin Iklan')->persistent('Close');
	return redirect('/');
});
Route::get('/pencarian', 'SearchController@searchResult');
Route::get('/pencarian/berita', 'SearchController@searchNews');
Route::get('/pencarian/komentar', 'SearchController@searchComments');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
	use SoftDeletes; 

	protected $fillable = [
		'rubric_id',
		'slug',
		'title',
		'content',
		'image',
		'image_source',
		'status',
		'keywords',
		'is_spreaded' 
	];

	public static function boot(){
		parent::boot();

		static::deleting(function($model){
			$model->highlight()->detach();
		});  
	}

	protected $dates = ['deleted_at'];

	public function getRubric($id){

	}

    public function rubric(){
    	return $this->belongsTo('App\Rubric');
    }

    public function highlight(){
    	return $this->belongsToMany('App\Highlight');
    }

    public function type(){
    	return $this->belongsToMany('App\Type');
    }

    public function user(){
    	return $this->belongsTo('App\User');
    }

    public function comment(){
    	return $this->hasMany('App\Comment');
    }

    public function getPhotoPathAttribute(){
        if($this->image != ''){
            return url('/img/data/news/'.$this->image);
        }
        else{
            return url('/img/data/news/default.png');
        }
    } 
}

app/Http/Controllers/ConfigController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use DB;
use Session;
use Alert;
use Validator;
use File;
use Hash;
use Auth;
use App\Configuration;

class ConfigController extends Controller
{
    public function index(){
    	$config = Configuration::find(1)->first();
    	if($config != NULL){
    		return view('config.index', compact('config'));
    	}
    	else{
    		abort(401);
    	}
    }

    public function update(Request $request, $id){
    	$data = Configuration::find($id); 
    	$config = Configuration::find($id);
    	if ($request->hasFile('logo')){
            $rules = [
                'logo' => 'required|image|mimes:jpeg,jpg,png',
            ];
            
            $messages = [
                'required' => 'Field harus di isi alias tidak boleh kosong',
                'image' => 'Logo harus berbenuk gambar',
                'mimes' => 'Image harus berekstensi JPEG, JPG, dan PNG'
            ];

            $validator = Validator::make($request->all(), $rules, $messages);
            if($validator->fails()) {
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data logo config"]);
                return redirect('config')->withErrors($validator)->withInput();
            }

            $config -> logo = $this->savePhoto($request->file('logo'));
            $config->save();
            if($data->avatar !== '') $this->deletePhoto($data->avatar);
            if($config){
	            Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil mengubah data logo"]);
	            return redirect('config');
	        }
	        else{
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data logo config"]);
                return redirect('config');
	        }
        }

        if($request->has('facebook')){
            $rules = [
                'facebook' => 'required|url',
                'twitter' => 'required|url',
                'email' => 'required|email',
            ];
            
            $messages = [
                'required' => 'Field harus di isi alias tidak boleh kosong',
                'image' => 'Logo harus berbenuk gambar',
                'mimes' => 'Image harus berekstensi JPEG, JPG, dan PNG',
                'email' => 'Email tidak valid',
                'url' => 'URL tidak valid'
            ];

            $validator = Validator::make($request->all(), $rules, $messages);
            if($validator->fails()) {
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data social network config"]);
                return redirect('config')->withErrors($validator)->withInput();
            }
            $config->update($request->all());
            if($config){
				Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil mengubah data social network"]);
	            return redirect('config');
	        }
	       	else{
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data social network"]);
                return redirect('config');
	        }
        }

        if($request->has('phone_number')){
            $rules = [
                'phone_number' => 'required|numeric',
                'mobile_number' => 'required|numeric',
                'fax_number' => 'required|numeric',
            ];
            
            $messages = [
                'required' => 'Field harus di isi alias tidak boleh kosong',
                'numeric.phone_number' => 'Nomor telepon tidak valid',
                'numeric.mobile_number' => 'Nomor handphone tidak valid',
                'numeric.fax_number' => 'Nomor fax tidak valid'
            ];

            $validator = Validator::make($request->all(), $rules, $messages);
            if($validator->fails()) {
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data config"]);
                return redirect('config')->withErrors($validator)->withInput();
            }
            $config->update($request->all());
            if($config){
				Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil mengubah data social network"]);
	            return redirect('config');
	        }
	       	else{
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data social network"]);
                return redirect('config');
	        }
        }

        if($request->has('web_name')){
            $rules = [
                'web_name' => 'required|string',
                'url' => 'required|url',
                'tagline' => '',
                'keywords' => 'string',
                'lat' => 'numeric',
                'long' => 'numeric',
                'address' => 'required',
            ];
            
            $messages = [
                'required' => 'Field harus di isi alias tidak boleh kosong',
                'url' => 'Web tidak valid',
                'numeric.lat' => 'Latitude tidak valid',
                'numeric.long' => 'Longitude tidak valid'
            ];

            $validator = Validator::make($request->all(), $rules, $messages);
            if($validator->fails()) {
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data general config"]);
                return redirect('config')->withErrors($validator)->withInput();
            }
            $config->update($request->all());
            if($config){
				Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil mengubah data general config"]);
	            return redirect('config');
	        }
	       	else{
                Session::flash('flash_notification', ["level"=>"danger", "message"=>"Oops, gagal mengubah data general config"]);
                return redirect('config');
	        }
        }
    }

    public function savePhoto(UploadedFile $photo) {
        $fileName = str_random(40) . '.' . $photo->guessClientExtension();
        $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'images/general';
        $photo -> move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename){
        $path = public_path() . DIRECTORY_SEPARATOR . 'images/general'.$filename;
        return File::delete($path);
    }
}
 

resources/views/config/index.blade.php
@extends('layouts.app2')
@section('title', 'Profile') 
@section('style')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/cropper/cropper.min.css') }}"/>
@endsection
@section('menu', 'profile')
{!! $errors->first('avatar', '<p class="help-block">:message</p>') !!}
@section('content')                        
    <div class="col-md-6 col-sm-4 col-xs-5">
        <form action="#" class="form-horizontal">
            <div class="panel panel-default">                                 
                <div class="panel-body">
                    <h3><span class="fa fa-user"></span>  Logo</h3>
                    <div class="text-center" id="user_image">
                        <img src="{{ $config->photo_path }}" width="400" height="250" class="img-thumbnail"/>
                    </div>                                    
                </div>
                <div class="panel-body form-group-separated">
                    
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Logo</label>                                        
                        <div class="col-md-9 col-xs-7">
                            <a href="#" class="btn btn-primary btn-block btn-rounded" data-toggle="modal" data-target="#modal_change_photo">Change</a>
                        </div>
                    </div>

                </div>
            </div>
        </form>
        <br>
        <form action="config/update/{{$config->id}}" class="form-horizontal" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="panel panel-default">                                
                <div class="panel-body">
                    <h3><span class="fa fa-user"></span> Social Network</h3>                                   
                </div>
                <div class="panel-body form-group-separated">
                    
                    <div class="form-group">                                       
                        <label class="col-md-3 col-xs-5 control-label"><span class="fa fa-facebook-square" aria-hidden="true">  Facebook</span></label>
                        <div class="col-md-9 col-xs-7">
                            <input type="text" name="facebook" value="{{ $config->facebook }}" class="form-control"/>
                            {!! $errors->first('facebook', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>

                    <div class="form-group">                                       
                        <label class="col-md-3 col-xs-5 control-label"><span class="fa fa-twitter-square" aria-hidden="true">  Twitter</span></label>
                        <div class="col-md-9 col-xs-7">
                            <input type="text" name="twitter" value="{{ $config->twitter }}" class="form-control"/>
                            {!! $errors->first('twitter', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>

                    <div class="form-group">                                       
                        <label class="col-md-3 col-xs-5 control-label"><span class="fa fa-cc" aria-hidden="true">  Email</span></label>
                        <div class="col-md-9 col-xs-7">
                            <input type="text" name="email" value="{{ $config->email }}" class="form-control"/>
                            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 col-xs-5">
                            <button class="btn btn-primary btn-rounded pull-right">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-6 col-sm-8 col-xs-7">
        <form action="config/update/{{$config->id}}" class="form-horizontal" method="post" >
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><span class="fa fa-pencil"></span> General</h3>
                </div>
                <div class="panel-body form-group-separated">
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Web Name</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="text" name="web_name" value="{{ $config->web_name }}" class="form-control"/>
                            {!! $errors->first('web_name', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">URL</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="text" name="url" value="{{ $config->url}}" class="form-control"/>
                            {!! $errors->first('url', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Tagline</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="text" name="tagline" value="{{ $config->tagline }}" class="form-control"/>
                            {!! $errors->first('tagline', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Keywords</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="text" name="keywords" value="{{ $config->keywords }}" class="form-control"/>
                            {!! $errors->first('keywords', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Maps Latitude</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="number" name="lat" value="{{ $config->lat }}" class="form-control"/>
                            {!! $errors->first('lat', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Maps Longitude</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="number" name="long" value="{{ $config->long }}" class="form-control"/>
                            {!! $errors->first('long', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Address</label>
                        <div class="col-md-9 col-xs-7">
                            <textarea class="form-control" name ="address" rows="5">{{ $config->address }}</textarea>
                            {!! $errors->first('address', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>                                          
                    <div class="form-group">
                        <div class="col-md-12 col-xs-5">
                            <button class="btn btn-primary btn-rounded pull-right">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
       <br>
        <form action="config/update/{{$config->id}}" class="form-horizontal" method="post" >
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><span class="fa fa-pencil"></span> Contact</h3>
                </div>
                <div class="panel-body form-group-separated">
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Phone Number</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="number" name="phone_number" value="{{ $config->phone_number }}" class="form-control" onkeypress="return event.charCode >= 48", placeholder="ex: 21837448" />
                            {!! $errors->first('phone_number', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Mobile Number</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="number" name="mobile_number" value="{{ $config->mobile_number }}" class="form-control" onkeypress="return event.charCode >= 48", placeholder="ex: 08747346374" />
                            {!! $errors->first('mobile_number', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-xs-5 control-label">Fax Number</label>
                        <div class="col-md-9 col-xs-7">
                            <input type="number" name="fax_number" value="{{ $config->fax_number }}" class="form-control" onkeypress="return event.charCode >= 48", placeholder="ex: 52133789893" />
                            {!! $errors->first('fax_number', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-xs-5">
                            <button class="btn btn-primary btn-rounded pull-right">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>       
    </div>
    <!-- MODALS -->
    <div class="modal animated fadeIn" id="modal_change_photo" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="smallModalHead">Change Logo</h4>
                </div>                    
                <form id="cp_crop" method="post" action="assets/crop_image.php">
                <div class="modal-body">
                    <div class="text-center">Photo only JPG, JPEG, and PNG.</div>                     
                </div>                    
                </form>
                <form action="config/update/{{$config->id}}" class="form-horizontal" method="post" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="modal-body form-horizontal form-group-separated">
                        <div class="form-group">
                            <label class="col-md-3 control-label">New Logo</label>
                            <div class="col-md-7">
                                <input type="file" multiple id="file-simple" name="logo"/>
                                {!! $errors->first('logo', '<p class="help-block">:message</p>') !!}
                            </div>                            
                        </div>                        
                    </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Accept</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    
    <!-- EOF MODALS -->
@endsection
@section('script')
    <script type='text/javascript' src='{{ asset('js/plugins/icheck/icheck.min.js') }}'></script>
    <script type="text/javascript" src="{{ asset('js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>  
    <script type="text/javascript" src="{{ asset('js/plugins/bootstrap/bootstrap-file-input.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/plugins/form/jquery.form.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/plugins/fileinput/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/actions.js') }}"></script>
    <script>
        $("#file-simple").fileinput({
                showUpload: false,
                showCaption: false,
                browseClass: "btn btn-danger",
                fileType: "any"
        });  
    </script>
@endsection