routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['isAdmin']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/delete-rubric/{id}', 'TrashController@destroyRubric');
	Route::get('/delete-type/{id}', 'TrashController@destroyType');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/delete-news/{id}', 'TrashController@destroyNews');
	Route::get('/restore-rubric/{id}', 'TrashController@restoreRubric');
	Route::get('/restore-type/{id}', 'TrashController@restoreType');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::get('/restore-news/{id}', 'TrashController@restoreNews'); 

	//Rubrik Controller
	Route::resource('/rubric', 'RubricController');
	Route::get('/rubric-order', 'RubricController@rubricOrder');
	Route::post('/rubric-order-save', 'RubricController@orderSave');
	//End Rubrik Controller

	//Tipe Controller
	Route::resource('/type', 'TypeController');
	//End Tipe Controller

	//Highlight Controller
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	//End Highlight Controller

	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	//End News Controller

	//Ads Controller
	Route::resource('/advertisement', 'AdvertisementController');
	//End Ads Controller

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::post('/spread-news/{news}', 'SubscribeController@spreadNews');

	//AccessLog
	Route::resource('/accesslog', 'AccessLogController');
	Route::post('/accesslog/export', 'AccessLogController@export');
	Route::post('/accesslog/delete', 'AccessLogController@delete');

	//Config
	Route::get('/config', 'ConfigController@index');
	Route::post('/config/update/{id}', 'ConfigController@update');
	Route::get('/log', 'LogController@index');
});

Route::group(['middleware' => ['isRedaktur']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	
	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	
	Route::resource('/profile', 'ProfileController'); 

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::get('/spread-news/{news}', 'SubscribeController@spreadNews');
	Route::get('/log', 'LogController@index');
});  
 
Route::group(['middleware' => ['isReporter']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 

Route::group(['middleware' => ['isUser']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 


//FRONT END 
Route::get('/', 'FrontEnd\IndexController@index');
Route::post('/user-store', 'UserController@userStore');
Route::post('/subscribe', 'SubscribeController@postSubscribe');
Route::get('berita/rubrik/{rubric}', 'FrontEnd\RubrikController@index');
Route::get('berita/rubrik/{rubric}/{news}', 'FrontEnd\NewsController@rubric_news');
Route::get('berita/fokus/{highlight}', 'FrontEnd\FokusController@index');
Route::get('berita/fokus/{highlight}/{news}', 'FrontEnd\NewsController@highlight_news');
Route::resource('/subscribe', 'SubscribeController');
Route::resource('/comment', 'CommentController');
Route::get('/request-ads', function(){
	Alert::message('Silahkan hubungi kami melalui email untuk pemasangan iklan di portal kami. Email : retorikakampus@gmail.com', 'Permohonan Izin Iklan')->persistent('Close');
	return redirect('/');
});
Route::get('/pencarian', 'SearchController@searchResult');
Route::get('/pencarian/berita', 'SearchController@searchNews');
Route::get('/pencarian/komentar', 'SearchController@searchComments');

app/Http/Controllers/StatisticController.php
<?php



namespace App\Http\Controllers;



use Illuminate\Http\Request;

use Symfony\Component\HttpFoundation\File\UploadedFile;

use App\Http\Requests;

use App\News;

use App\User;

use App\AccessLog;

use App\Rubric;

use Session;

use Auth;

use Validator;

use File;

use Carbon\Carbon;



class StatisticController extends Controller 

{

    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function index(Request $request)

    {

        try{

            $users = User::all();

            $news = News::count();

            $news_user = News::where('created_by', Auth::user()->id)->count();

            $rubrics = Rubric::all();



            File::put(public_path('data_rubric.json'),$rubrics);

            $visitors = AccessLog::whereDate('created_at', Carbon::now()->format('Y-m-d'))->distinct()->count(["ip"]);

            // foreach ($users as $user) {

            //     if($user->level_id != 1){

            //         $statistic[$user->username]=News::where('created_by', $user->username)->count();

            //     }

            // }



            $usersNews=[];

            foreach ($users as $user){

                $count = count(News::where('created_by', $user->id)->get());

                $usersNews[]=['level_id'=>$user->level_id, 'name'=>$user->name, 'username'=>$user->username, 'count'=>$count];

            }

            $cek=collect($usersNews)->sortByDesc('count')->values()->all();



            //chart

            if(!$request->has('logVisitType'))

                $logVisitType='daily';

            else {

                $logVisitType = $request->logVisitType;

            }

            $AccessLogs = [];

            

            if($logVisitType == 'hourly'){

                for($i=0; $i<24; $i++){

                    $today = Carbon::now();

                    $start_hour = Carbon::create($today->year, $today->month, $today->day, $i, 0, 0);

                    if($i<23){

                        $end_hour = Carbon::create($today->year, $today->month, $today->day, $i+1, 0, 0);

                    }

                    else {

                        $end_hour = Carbon::create($today->year, $today->month, $today->day+1, 0, 0, 0);

                    }

                    $log = AccessLog::where('created_at', '>=', $start_hour->toDateTimeString())

                                    ->where('created_at', '<', $end_hour->toDateTimeString())

                                    ->select('ip')->distinct()->count(["ip"]);

                    $AccessLogs[]= ['y'=>$i, 'a'=>$log];

                }

            }

            else {

                for($i=6;$i>=0;$i--){

                    if($logVisitType=='daily'){

                        $now = Carbon::now()->subDays($i)->format('Y-m-d');

                        $log = AccessLog::whereDate('created_at', $now)->select('ip')->distinct()->count(["ip"]);

                    } else if($logVisitType=='weekly'){

                        $now = Carbon::now()->subWeeks($i)->format('Y-m-d');

                        $lastWeek = Carbon::now()->subWeeks($i+1)->format('Y-m-d');

                        $log = AccessLog::whereDate('created_at', '>', $lastWeek)

                                        ->whereDate('created_at', '<=', $now)

                                        ->select('ip')->distinct()->count(["ip"]);

                    } else {

                        $now = Carbon::now()->subMonths($i)->format('Y-m-d');

                        $lastWeek = Carbon::now()->subMonths($i+1)->format('Y-m-d');

                        $log = AccessLog::whereDate('created_at', '>', $lastWeek)

                                        ->whereDate('created_at', '<=', $now)

                                        ->select('ip')->distinct()->count(["ip"]);

                    }

                    $AccessLogs[]= ['y'=>$now, 'a'=>$log];

                }

            } 



            if(!$request->has('logRubricsType'))

                $logRubricsType='today';

            else {

                $logRubricsType = $request->logRubricsType;

            }

            $rubricsLogs = [];

            $rubrics2 = Rubric::all();

            foreach ($rubrics2 as $f_rubrics2) {

                if($logRubricsType=='today'){

                    $now = Carbon::now()->format('Y-m-d');

                    $log = AccessLog::whereDate('created_at', $now)

                                ->where('path', 'like', '%'.$f_rubrics2->slug.'%')

                                ->distinct()

                                ->count(['ip']);

                } else if($logRubricsType=='thisweek'){

                    $now = Carbon::now()->format('Y-m-d');

                    $lastWeek = Carbon::now()->subWeeks(1)->format('Y-m-d');

                    $log = AccessLog::whereDate('created_at', '<=', $now)

                                ->whereDate('created_at', '>', $lastWeek)

                                ->where('path', 'like', '%'.$f_rubrics2->slug.'%')

                                ->distinct()

                                ->count(['ip']);

                } else {

                    $now = Carbon::now()->format('Y-m-d');

                    $lastMonth = Carbon::now()->subMonths(1)->format('Y-m-d');

                    $log = AccessLog::whereDate('created_at', '<=', $now)

                                ->whereDate('created_at', '>', $lastMonth)

                                ->where('path', 'like', '%'.$f_rubrics2->slug.'%')

                                ->distinct()

                                ->count(['ip']);

                }

                $rubricsLogs[] = ['y'=>$f_rubrics2->name, 'a'=>$log];

            }

            $user_news = News::where('created_by', Auth::user()->id)->orderBy('created_at', 'desc')->take(20)->get();
            $userNewsLogs = [];
            foreach ($user_news as $f_user_news) {
                $userNewsLogs[] = ['y'=>$f_user_news->title, 'a'=>$f_user_news->views];
            }

            return view("home", compact('users', 'news','news_user', 'rubrics', 'statistic', 'visitors', 'cek', 'AccessLogs', 'rubricsLogs', 'logVisitType', 'logRubricsType', 'userNewsLogs'));

        }

        // catch (\Illuminate\Database\QueryException $e) {

        //     return \Response::view('errors.query',array(),500);

        // }

        catch (\Exception $e) {

            return \Response::view('errors.500',array(),500);

        }

    }  



    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        //

    }



    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(Request $request)

    {

        //

    }



    /**

     * Display the specified resource.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function show($id)

    {

        //

    }



    /**

     * Show the form for editing the specified resource.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function edit($id)

    {

        //

    }



    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function update(Request $request, $id)

    {

        //

    }



    /**

     * Remove the specified resource from storage.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function destroy($id)

    {

        //

    }

}

resources/views/statistic/create.blade.php
@extends('layouts.app')
	@section('content')
		<div class= "container">
			<div class= "row">
				<div class= "col-md-12">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3>New Highlight</h3>
						</div>
						<div class="panel-body">
							{!! Form::open(['route' => 'highlight.store', 'files'=>true]) !!}
								@include('highlight.form')
							{!! Form::close() !!}	
						</div>
					</div>
				</div>
			</div> 
		</div>
	@endsection

resources/views/statistic/edit.blade.php
@extends('layouts.app')
	@section('content')
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3>Edit Highlight '{{ $highlight->name }}'</h3>
						</div>
						<div class="panel-body">
							{!! Form::model($highlight, ['route'=> ['highlight.update', $highlight], 'method'=>'patch']) !!}
		                        @include('highlight.form', ['model'=>$highlight])
		                    {!! Form::close() !!} 
						</div>
					</div>
				</div>
			</div>
		</div>
	@endsection

resources/views/statistic/form.blade.php
<div class= " form-group { !! $errors->has('name') ? 'has-error' : '' !!}">
	{!! Form::label('name', 'Name') !!}
	{!! Form::text('name', null, ['class' =>'form-control', 'placeholder' => 'Ketik nama rubric...']) !!}
	{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>

<div class= " form-group { !! $errors->has('description') ? 'has-error' : '' !!}">
	{!! Form::label('description' , 'description') !!}
	{!! Form::text('description', null, ['class' =>'form-control', 'placeholder' => 'Ketik nama rubric...']) !!}
	{!! $errors->first('description', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('image') ? 'has-error' : '' !!}">
	{!! Form::label('image', 'Highlight Image ( jpg,jpeg,png )') !!}
	{!! Form::file('image') !!}
	{!! $errors->first('image', '<p class="help-block">:message</p>')  !!}
	@if (isset($model) && $model->image !== '' )
	<div class= "row">
		<div class= "col-md-6">
			<br>
			<p>Current iamge:</p>
			<div class= "thumbnail">
				<img src = "{{ url('/img/highlight/' . $model->image) }}" class="img-rounded" width="200" height="200">
			</div>
		</div>
	</div>
	@endif
	@if (isset($model) && $model->image == '')
	<div class= "row">
		<div class= "col-md-6">
			<br>
			<p>Current image:</p>
			<div class= "thumbnail">
				<img src = "{{ url('/img/highlight/contoh.jpg') }}" class="img-rounded" width="200" height="200">
			</div>
		</div>
	</div>
	@endif
</div>

<center>
<a href="{{ route('highlight.index') }}" class="btn btn-warning">Cancel</a>
{!! Form::submit( isset( $model) ? 'Update' : 'Save', [ 'class'=> 'btn btn-primary']) !!}
</center>

resources/views/statistic/index.blade.php
@extends('layouts.app')
@section('content')
    <div class= "container">
        <div class= "row">
            <div class= "col-md-12">
                    <h3> Statistics  
                    </h3>
                
                <table class= "table table-hover">
                    <thead>
                        <tr>
                            <td>No</td>
                            <td>Member</td>
                            <td>Role</td>
                            <td>News</td>
                        </tr> 
                    </thead>
                    <tbody>
                        <?php $counter=1; ?>
                        @foreach($users as $user)
                            @if($user->level_id != 1 )
                            <tr>
                                <td>{{ $counter++ }}</td>
                                <td>{{ $user -> name }}</td>
                                <td>
                                    @if($user->level_id == 2)
                                        {{'Redaktur'}}
                                    @elseif($user->level_id == 3)
                                        {{'Reporter'}}
                                    @else
                                        {{'Member'}}
                                    @endif                                    
                                </td>
                                <td>{{ $statistic[$user->username] }}</td>
                                
                            </tr>
                            @endif
                        @endforeach
                    </body>
                </table>
            </div>
        </div>
    </div>
@endsection