routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['isAdmin']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/delete-rubric/{id}', 'TrashController@destroyRubric');
	Route::get('/delete-type/{id}', 'TrashController@destroyType');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/delete-news/{id}', 'TrashController@destroyNews');
	Route::get('/restore-rubric/{id}', 'TrashController@restoreRubric');
	Route::get('/restore-type/{id}', 'TrashController@restoreType');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::get('/restore-news/{id}', 'TrashController@restoreNews'); 

	//Rubrik Controller
	Route::resource('/rubric', 'RubricController');
	Route::get('/rubric-order', 'RubricController@rubricOrder');
	Route::post('/rubric-order-save', 'RubricController@orderSave');
	//End Rubrik Controller

	//Tipe Controller
	Route::resource('/type', 'TypeController');
	//End Tipe Controller

	//Highlight Controller
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	//End Highlight Controller

	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	//End News Controller

	//Ads Controller
	Route::resource('/advertisement', 'AdvertisementController');
	//End Ads Controller

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::post('/spread-news/{news}', 'SubscribeController@spreadNews');

	//AccessLog
	Route::resource('/accesslog', 'AccessLogController');
	Route::post('/accesslog/export', 'AccessLogController@export');
	Route::post('/accesslog/delete', 'AccessLogController@delete');

	//Config
	Route::get('/config', 'ConfigController@index');
	Route::post('/config/update/{id}', 'ConfigController@update');
	Route::get('/log', 'LogController@index');
});

Route::group(['middleware' => ['isRedaktur']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::get('/delete-highlight/{id}', 'TrashController@destroyHighlight');
	Route::get('/restore-highlight/{id}', 'TrashController@restoreHighlight');
	Route::resource('/highlight', 'HighlightController');
	Route::get('/highlight-order', 'HighlightController@highlightOrder');
	Route::post('/highlight-order-save', 'HighlightController@orderSave');
	
	//News Controller
	Route::resource('/news', 'NewsController');
	Route::post('/news/updateStatus/{id}', 'NewsController@updateStatus');
	
	Route::resource('/profile', 'ProfileController'); 

	//Member controller
	Route::resource('/member', 'UserController');
	Route::get('/user-confirm/{id}', 'UserController@userConfirm');
	Route::get('/spread-news/{news}', 'SubscribeController@spreadNews');
	Route::get('/log', 'LogController@index');
});  
 
Route::group(['middleware' => ['isReporter']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::get('/trash', 'TrashController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 

Route::group(['middleware' => ['isUser']], function () {
	Route::get('home', 'StatisticController@index');
	Route::post('home', 'StatisticController@index');
	Route::resource('/news', 'NewsController');
	Route::resource('/profile', 'ProfileController');
	Route::get('/log', 'LogController@index');
}); 


//FRONT END 
Route::get('/', 'FrontEnd\IndexController@index');
Route::post('/user-store', 'UserController@userStore');
Route::post('/subscribe', 'SubscribeController@postSubscribe');
Route::get('berita/rubrik/{rubric}', 'FrontEnd\RubrikController@index');
Route::get('berita/rubrik/{rubric}/{news}', 'FrontEnd\NewsController@rubric_news');
Route::get('berita/fokus/{highlight}', 'FrontEnd\FokusController@index');
Route::get('berita/fokus/{highlight}/{news}', 'FrontEnd\NewsController@highlight_news');
Route::resource('/subscribe', 'SubscribeController');
Route::resource('/comment', 'CommentController');
Route::get('/request-ads', function(){
	Alert::message('Silahkan hubungi kami melalui email untuk pemasangan iklan di portal kami. Email : retorikakampus@gmail.com', 'Permohonan Izin Iklan')->persistent('Close');
	return redirect('/');
});
Route::get('/pencarian', 'SearchController@searchResult');
Route::get('/pencarian/berita', 'SearchController@searchNews');
Route::get('/pencarian/komentar', 'SearchController@searchComments');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
	use SoftDeletes; 

	protected $fillable = [
		'rubric_id',
		'slug',
		'title',
		'content',
		'image',
		'image_source',
		'status',
		'keywords',
		'is_spreaded' 
	];

	public static function boot(){
		parent::boot();

		static::deleting(function($model){
			$model->highlight()->detach();
		});  
	}

	protected $dates = ['deleted_at'];

	public function getRubric($id){

	}

    public function rubric(){
    	return $this->belongsTo('App\Rubric');
    }

    public function highlight(){
    	return $this->belongsToMany('App\Highlight');
    }

    public function type(){
    	return $this->belongsToMany('App\Type');
    }

    public function user(){
    	return $this->belongsTo('App\User');
    }

    public function comment(){
    	return $this->hasMany('App\Comment');
    }

    public function getPhotoPathAttribute(){
        if($this->image != ''){
            return url('/img/data/news/'.$this->image);
        }
        else{
            return url('/img/data/news/default.png');
        }
    } 
}

app/Http/Controllers/FrontEnd/NewsController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Rubric;
use App\Highlight;
use App\Type;
use App\News;
use App\Advertisement;
use App\User;
use App\AccessLog;
use App\Configuration;
use Carbon\Carbon;
use DB;


class NewsController extends Controller
{


    public function rubric_news($rubric_slug, $news_slug, Request $request)
    {
        $last7Days = Carbon::now()->subDays(7);
        $rubrics = Rubric::noParent()->orderBy('order')->get();
        $highlights = Highlight::whereNotNull('order')->orderBy('order')->get();
        $rubric = Rubric::where('slug', $rubric_slug)->first();
        $headlines = News::all();
        $rubric_news = Rubric::find($rubric->id)->news()->orderBy('created_at', 'desc')->paginate(3);
        $news = News::where('rubric_id', $rubric->id)->where('slug', $news_slug)->first();
        $Acclog_check = AccessLog::where('path', 'like', '%'.$news_slug.'%')->where('ip', $request->getClientIp())->count();
        if($Acclog_check==0){
            DB::table('news')->where('rubric_id', $rubric->id)->where('slug', $news_slug)->update(['views'=>$news->views + 1]);
        }
        $news = News::where('rubric_id', $rubric->id)->where('slug', $news_slug)->first();
        $user = User::where('id', $news->created_by)->first();
        $recent_news = News::orderBy('created_at','desc')->take(5)->where('status', 'published')->get();
        $popular_news = News::query()->where('created_at', '>=', $last7Days)->orderBy('views', 'desc')->where('status', 'published')->take(5)->get();
        $ads1 = Advertisement::where('type','berita')->where('order',1)->first();
        $ads2 = Advertisement::where('type','berita')->where('order',2)->first();
        $ads3 = Advertisement::where('type','berita')->where('order',3)->first();
        $ads4 = Advertisement::where('type','berita')->where('order',4)->first();
        $ads5 = Advertisement::where('type','berita')->where('order',5)->first();
        $config = Configuration::find(1);
        $comments = $news->comment()->orderBy('id','asc')->paginate(6);
        return view('frontend.beritaRubrik', compact('rubric', 'highlights', 'recent_news', 'popular_news', 'rubrics','headlines', 'news', 'rubric_slug', 'rubric_news', 'ads1', 'ads2', 'ads3', 'ads4', 'ads5','comments','user','config'));
    }

    public function highlight_news($highlight_slug, $news_slug, Request $request)
    {
        $last7Days = Carbon::now()->subDays(7);
        $rubrics = Rubric::noParent()->orderBy('order')->get();
        $highlights = Highlight::whereNotNull('order')->orderBy('order')->get();
        $highlight = Highlight::where('slug', $highlight_slug)->first();
        $headlines = News::all();
        $highlight_news = Highlight::find($highlight->id)->news()->orderBy('created_at', 'desc')->paginate(3);
        $news = Highlight::find($highlight->id)->news()->where('slug', $news_slug)->first();
        $Acclog_check = AccessLog::where('path', 'like', '%'.$news_slug.'%')->where('ip', $request->getClientIp())->count();
        if($Acclog_check==0){
            DB::table('news')->where('rubric_id', $news->rubric_id)->where('slug', $news_slug)->update(['views'=>$news->views + 1]);
        }
        $news = Highlight::find($highlight->id)->news()->where('slug', $news_slug)->first();
        $user = User::where('id', $news->created_by)->first();
        $recent_news = News::orderBy('created_at','desc')->take(5)->where('status', 'published')->get();
        $popular_news = News::query()->where('created_at', '>=', $last7Days)->orderBy('views', 'desc')->where('status', 'published')->take(5)->get();
        $ads1 = Advertisement::where('type','fokus')->where('order',1)->first();
        $ads2 = Advertisement::where('type','fokus')->where('order',2)->first();
        $ads3 = Advertisement::where('type','fokus')->where('order',3)->first();
        $ads4 = Advertisement::where('type','fokus')->where('order',4)->first();
        $ads5 = Advertisement::where('type','fokus')->where('order',5)->first();
        $config = Configuration::find(1);
        $comments = $news->comment()->orderBy('id','asc')->paginate(6);
        return view('frontend.beritaFokus', compact('highlight', 'highlights', 'recent_news', 'popular_news', 'rubrics', 'headlines', 'news', 'highlight_slug', 'highlight_news', 'ads1', 'ads2', 'ads3','ads4', 'ads5', 'user', 'comments', 'config'));
    }
}

resources/views/news/create.blade.php
@extends('layouts.app2')

@section('style')

<script type="text/javascript" src="{{ asset('nicEdit/nicEdit.js')}}"></script> 
<script type="text/javascript">
//<![CDATA[
        
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });

  //]]>
</script>

@endsection

@section('title', 'News')

@section('menu', 'news')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading">

            <h3 class="panel-title">News

            </h3>                                  

        </div>

        <div class="panel-body">

            {!! Form::open(['route' => 'news.store', 'files'=>true]) !!}

                @include('news.form')

            {!! Form::close() !!}   

        </div>

    </div>

@endsection



@section('script')

<script type='text/javascript' src="{{ asset('js/plugins/icheck/icheck.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/actions.js') }}"></script> 

@endsection 

resources/views/news/edit.blade.php
@extends('layouts.app2')

@section('style')

<script type="text/javascript" src="{{ asset('nicEdit/nicEdit.js')}}"></script> 
<script type="text/javascript">
//<![CDATA[
        
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });

  //]]>
</script>

@endsection

@section('title', 'Edit News')

@section('menu', 'edit news')

@section('content') 

    <div class="panel panel-default">

		<div class="panel-heading">

			<h3>Edit News</h3>

		</div>

		<div class="panel-body">

			{!! Form::model($news, ['route'=> ['news.update', $news], 'method'=>'patch', 'files'=>true]) !!}

	            @include('news.form', ['model'=>$news])

	        {!! Form::close() !!} 

		</div>

	</div>

@endsection



@section('script')

<script type="text/javascript" src="{{ asset('js/actions.js') }}"></script> 

@endsection 

resources/views/news/form.blade.php
<div class= " form-group { !! $errors->has('title') ? 'has-error' : '' !!}">

	{!! Form::label('title', 'Title') !!}

	{!! Form::text('title', null, ['class' =>'form-control', 'placeholder' => 'Ketik judul berita...']) !!}

	{!! $errors->first('title', '<p class="help-block">:message</p>') !!}

</div>



<div class= " form-group { !! $errors->has('content') ? 'has-error' : '' !!}">

	{!! Form::label('content' , 'Content') !!}

	{!! Form::textarea('content', null, ['class' =>'form-control', 'placeholder' => 'Ketik isi berita...']) !!}

	{!! $errors->first('content', '<p class="help-block">:message</p>') !!}

</div> 



<div class= " form-group { !! $errors->has('keywords') ? 'has-error' : '' !!}">

	{!! Form::label('keywords', 'Keywords') !!}

	{!! Form::text('keywords', null, ['class' =>'form-control', 'placeholder' => 'Ketik keywords berita...']) !!}

	{!! $errors->first('keywords', '<p class="help-block">:message</p>') !!}

</div>



<div class= " form-group { !! $errors->has('rubric') ? 'has-error' : '' !!}">

	@if(Auth::user()->level_id!=4)

		{!! Form::label('rubric' , 'Rubric') !!}

		@if(isset($news))

			{!! Form::select('rubric', ['' => ''] + $pluck, (!empty($news->rubric_id)? $news->rubric_id:'null'), ['class' =>'form-control js-selectize']) !!}

		@else

			{!! Form::select('rubric', ['' => ''] + $pluck, null, ['class' =>'form-control js-selectize']) !!}

		@endif

	@else

		{!! Form::text('rubric', 1, ['class' =>'hidden']) !!}

	@endif

	{!! $errors->first('rubric', '<p class="help-block">:message</p>') !!}

</div>


@if(Auth::user()->level_id == 1 or Auth::user()->level_id == 2)
	<div class= " form-group { !! $errors->has('highlight') ? 'has-error' : '' !!}">

		{!! Form::label('highlight' , 'Highlight') !!}

		{!! Form::select('highlight[]', [ '' => '' ]+App\Highlight::pluck('name','id')->all(), null, ['class' =>'form-control js-selectize', 'multiple']) !!}

		{!! $errors->first('highlight', '<p class="help-block">:message</p>') !!}

	</div>
@endif


	<div class= " form-group { !! $errors->has('type') ? 'has-error' : '' !!}">

		@if(Auth::user()->level_id!=4 and Auth::user()->level_id!=3)

			{!! Form::label('type' , 'Headline') !!}

			{!! Form::select('type[]', [ '' => '' ]+App\Type::pluck('name','id')->all(), null, ['class' =>'form-control js-selectize']) !!}

		@else

			{!! Form::text('type[]', 1, ['class' =>'hidden']) !!}

		@endif

		{!! $errors->first('type', '<p class="help-block">:message</p>') !!}

	</div>



<div class="form-group {!! $errors->has('image') ? 'has-error' : '' !!}">

	{!! Form::label('image', 'News Image ( jpg,jpeg,png )') !!}

	{!! Form::file('image') !!}

	{!! $errors->first('image', '<p class="help-block">:message</p>')  !!}

	@if (isset($model) && $model->image !== '' )

	<div class= "row">

		<div class= "col-md-6">

			<br>

			<p>Current iamge:</p>

			<div class= "thumbnail">

				<img src = "{{ url('/img/data/news/'. $model->image) }}" class="img-rounded" width="200" height="200">

			</div>

		</div>

	</div>

	@endif

	@if (isset($model) && $model->image == '')

	<div class= "row">

		<div class= "col-md-6">

			<br>

			<p>Current image:</p>

			<div class= "thumbnail">

				<img src = "{{ url('/img/data/news/default.png') }}" class="img-rounded" width="200" height="200">

			</div>

		</div>

	</div>

	@endif

</div>

<div class= " form-group { !! $errors->has('keywords') ? 'has-error' : '' !!}">

	{!! Form::label('image_source', 'Image Source') !!}

	{!! Form::text('image_source', null, ['class' =>'form-control', 'placeholder' => 'Ketik url sumber gambar berita']) !!}

	{!! $errors->first('keywords', '<p class="help-block">:message</p>') !!}

</div>

@if(isset($news))
	@if(Auth::user()->id == $news->created_by)
		<div class= " form-group ">

			{!! Form::label('save_as' , 'Save as') !!}

			{!! Form::select('save_as', [ 'draft' => 'Draft', 'news' => 'News' ], ($news->is_draft? 'draft' : 'news') , ['class' =>'form-control js-selectize']) !!}

		</div>
	@endif

@else
	<div class= " form-group ">

		{!! Form::label('save_as' , 'Save as') !!}

		{!! Form::select('save_as', [ 'draft' => 'Draft', 'news' => 'News' ], null, ['class' =>'form-control js-selectize']) !!}

	</div>
@endif

<center>

<a href="{{ route('news.index') }}" class="btn btn-warning">Cancel</a>

{!! Form::submit( isset( $model) ? 'Simpan' : 'Kirim Berita', [ 'class'=> 'btn btn-primary']) !!}

</center>

resources/views/news/search.blade.php
@extends('layouts.app2')

@section('title', 'News')

@section('menu', 'news')

@section('content') 

    <div class="panel panel-default">

        <div class="panel-heading"> 

            <h3 class="panel-title">News

            </h3>

            <div class="btn-group pull-right">

                <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i> Export Data</button>

                <ul class="dropdown-menu">

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'json',escape:'false'});"><img src='img/icons/json.png' width="24"/> JSON</a></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'json',escape:'false',ignoreColumn:'[2,3]'});"><img src='img/icons/json.png' width="24"/> JSON (ignoreColumn)</a></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'json',escape:'true'});"><img src='img/icons/json.png' width="24"/> JSON (with Escape)</a></li>

                    <li class="divider"></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'xml',escape:'false'});"><img src='img/icons/xml.png' width="24"/> XML</a></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'sql'});"><img src='img/icons/sql.png' width="24"/> SQL</a></li>

                    <li class="divider"></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'csv',escape:'false'});"><img src='img/icons/csv.png' width="24"/> CSV</a></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'txt',escape:'false'});"><img src='img/icons/txt.png' width="24"/> TXT</a></li>

                    <li class="divider"></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'excel',escape:'false'});"><img src='img/icons/xls.png' width="24"/> XLS</a></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'doc',escape:'false'});"><img src='img/icons/word.png' width="24"/> Word</a></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'powerpoint',escape:'false'});"><img src='img/icons/ppt.png' width="24"/> PowerPoint</a></li>

                    <li class="divider"></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'png',escape:'false'});"><img src='img/icons/png.png' width="24"/> PNG</a></li>

                    <li><a href="#" onClick ="$('#customers2').tableExport({type:'pdf',escape:'false'});"><img src='img/icons/pdf.png' width="24"/> PDF</a></li>

                </ul>

            </div>                                    

        </div>

        <div class="panel-body">

            <span>Tambah: 

                <a href="{{ route('news.create') }}" class= "btn btn-info btn-sm" >+</a>

            <span>

            <div class="table-responsive">

                <table id="customers2" class="table datatable">

                    <thead>

                        <tr>

                            <th>Image</th>

                            <th>Rubric</th>

                            <th>Type</th>

                            <th>Highlight</th>

                            <th>Judul</th>

                            <th>Created_by</th>

                            <th>Edited_by</th>

                            <th>Published_by</th>

                            <th style="width:15%">Status</th>

                            <th colspan="3"><center>Action</center></th>

                        </tr>

                    </thead>

                    <tbody>

                        @forelse($news as $f_news)

                            <tr>

                                <td><img src="{{ $f_news -> photo_path }}" width="30" height="30"></td>

                                <td>{{ $f_news -> rubric -> name }}</td>

                                <td> 

                                    @foreach ($f_news -> type as $type)

                                    <span class="label label-primary"><i class="fa fa-btn fa-tags"></i>{{ $type->name }}</span>

                                        @endforeach

                                    </td>

                                <td>

                                    @foreach ($f_news -> highlight as $highlight)

                                        <span class="label label-primary"><i class="fa fa-btn fa-tags"></i>{{ $highlight->name }}</span>

                                    @endforeach

                                </td>

                                <td>{{ $f_news -> title }}</td>

                                <td>{{ App\User::where('id', $f_news -> created_by)->first()->name }}</td>

                                @if($f_news->edited_by != NULL) 

                                    <td>{{ App\User::where('id', $f_news -> edited_by)->first()->name }}</td>

                                @else
                                        
                                    <td></td>

                                @endif
                                @if($f_news->approved_by != NULL)

                                    <td>{{ App\User::where('id', $f_news -> approved_by)->first()->value('name') }}</td>

                                @else

                                    <td></td>

                                @endif

                                <td>

                                    @if(Auth::user()->level_id == 3 or Auth::user()->level_id == 4)

                                        {{ $f_news -> status }}

                                    @else

                                        {!! Form::open(['url' => 'news/updateStatus/'.$f_news->id, 'method' => 'post']) !!}

                                        {!! Form::select('status_change', [ 'published' => 'published', 'pending' => 'pending' ], $f_news -> status,['onchange' => 'this.form.submit()', 'class'=>'form-control js-selectize']) !!}

                                        {!! Form::close() !!}

                                    @endif

                                </td>

                                <td>
                                    <a href="{{url('berita/rubrik/'.$f_news->rubric->slug.'/'.$f_news->slug)}}" class="btn btn-sm btn-info">View</a>
                                        
                                </td>

                                <td>
                                    
                                    <a href="{{ route('news.edit', $f_news->id) }}" class = "btn btn-sm btn-success">Edit</a>

                                </td>

                                <td>

                                    @if(Auth::user()->id == $f_news->created_by)

                                        {!! Form::model($f_news, ['route' => ['news.destroy', $f_news], 'method' => 'delete', 'class' => 'form-inline'] ) !!}

                                        {!! Form::submit('delete', ['class'=>'btn btn-sm btn-danger js-submit-confirm']) !!}

                                        {!! Form::close() !!}

                                    @endif

                                </td> 

                            </tr>

                        @empty

                            <td colspan="10"><center><h2>:(</h2><p>Berita yang anda cari tidak ada..</p></center></td>

                        @endforelse

                    </tbody>

                </table> 

                {{ $news->appends(['query'=>$query])->links() }}                                   

            </div>

        </div>

    </div>

@endsection



@section('script')

<script type='text/javascript' src="{{ asset('js/plugins/icheck/icheck.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/tableexport/tableExport.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jquery.base64.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/tableexport/html2canvas.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jspdf/libs/sprintf.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jspdf/jspdf.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/tableexport/jspdf/libs/base64.js') }}"></script> 

<script type="text/javascript" src="{{ asset('js/actions.js') }}"></script> 

@endsection 